version: '3'

services:
  spring-app-1:
    image: spring-app-1
    container_name: spring-app-1
    build:
      context: ./spring-boot-app-one/springapp1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  spring-app-2:
    image: spring-app-2
    container_name: spring-app-2
    build:
      context: ./spring-boot-app-two/spring-app-2/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"